Upload surefire reports for maven builds

diff --git a/.github/workflows/validate-jar-maven.yml b/.github/workflows/validate-jar-maven.yml
--- a/.github/workflows/validate-jar-maven.yml
+++ b/.github/workflows/validate-jar-maven.yml
@@ -79,13 +79,35 @@ jobs:
         if: failure()
         run: |
           readarray -d '' reports < <(find . -wholename "*/target/surefire-reports/*.txt" -print0)
-          for report in "${reports[@]}"; do
-            #echo "Current item: $report"
-            if ! grep -q 'Failures: 0, Errors: 0' $report; then
-              echo $report
-              cat $report >> $GITHUB_STEP_SUMMARY
+          if [ ${#reports[@]} -eq 0 ]; then
+            echo "No surefire reports found"
+          else
+            errorOrFailureReports=()
+            for report in "${reports[@]}"; do
+              if ! grep -q 'Failures: 0, Errors: 0' $report; then
+                errorOrFailureReports+=($report)
+              fi
+            done
+            errorOrFailureReportCount=${#errorOrFailureReports[@]}
+            if [ "$errorOrFailureReportCount" -gt "10" ]; then
+              echo ":rotating_light: Printing first 10 of $errorOrFailureReportCount unit test files with failure(s) and/or error(s)." >> $GITHUB_STEP_SUMMARY
+              for i in {0..10}
+              do
+                cat "${errorOrFailureReports[$i]}" >> $GITHUB_STEP_SUMMARY
+              done
+            else 
+              echo ":rotating_light: Found $errorOrFailureReportCount unit test files with failure(s) and/or error(s)." >> $GITHUB_STEP_SUMMARY
+              for report in "${errorOrFailureReports[@]}"; do
+                cat "$report" >> $GITHUB_STEP_SUMMARY
+              done
             fi
-          done
+          fi
+      - name: Upload Surefire Reports
+        uses: actions/upload-artifact@v4
+        if: failure()
+        with:
+          name: surefire-reports-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
+          path: "**/target/surefire-reports/"
       - name: Ready for upload
         if: success() && inputs.upload-artifact == 'true'
         run: |
@@ -99,6 +121,7 @@ jobs:
           path: libs
           retention-days: 4
           overwrite: true
+
 
   post-to-slack-if-failure:
     needs: validate-maven-build
